name: Pages Rebuild

on:
  workflow_dispatch:

permissions:
  pages: write

jobs:
  trigger:
    runs-on: [self-hosted]
    steps:
      - name: Trigger Pages build
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        with:
          script: |
            const result = await github.request('POST /repos/{owner}/{repo}/pages/builds', { owner: context.repo.owner, repo: context.repo.repo, source: 'main:/' });
            core.notice(`Requested Pages build: ${JSON.stringify(result.data || result)}`);
